### ISSUE TITLE
Get zero latitude and longitude

### ISSUE THREAD

**Issue by sanjaygubaju** [delight-im/Android-SimpleLocation#15]
Both latitude and longitude is 0.0.

**Comment by ocram** [comment]
Right after creating the instance, can you add

```java
mySimpleLocation.setListener(new SimpleLocation.Listener() {});
```

and implement the method from that interface `SimpleLocation.Listener`? This way, you should be informed as soon as the location has been detected.

Apart from that, please check the permissions, as always.

Does that help?

**Comment by jorgecasariego** [comment]
I'm having the same problem. In some cases it works perfect and others returns 0.

**Comment by ocram** [comment]
@jorgecasariego Did you try the same solution (suggested above)?

**Comment by jorgecasariego** [comment]
Yes, I read also other issues here. I'm testing now. It isn't always but in some places I receive 0 0

**Comment by huxaiphaer** [comment]
`mySimpleLocation.setListener(new SimpleLocation.Listener() {});`
It worked like charm. :-)
But i suggest please add this in the documentation.

**Comment by ocram** [comment]
@huxaiphaer Thanks! You're right, that is definitely needed. Sorry that it was missing so far. A paragraph has been added to the documentation in https://github.com/delight-im/Android-SimpleLocation/commit/adf899da6b9fd55f860979e88e9c247554377683.

**Comment by huxaiphaer** [comment]
That's fantastic, great Macro.
