### ISSUE TITLE
Get LatLong with Address

### ISSUE THREAD

**Issue by Ramonzo** [delight-im/Android-SimpleLocation#18]
Is possible get de Lat and Long with the Address in this library?

**Comment by whencut** [comment]
` final double latitude = location.getLatitude();
                final double longitude = location.getLongitude();`

**Comment by ocram** [comment]
What this library provides is the (numeric) location using latitude and longitude, i.e. coordinates on the map.

What you want sounds like [reverse geocoding](https://en.wikipedia.org/wiki/Reverse_geocoding), which is not included. This requires a database and cannot be done in a purely algorithmic way.
