### ISSUE TITLE
Location not updated in background service

### ISSUE THREAD

**Issue by kulwinderSingh30** [delight-im/Android-SimpleLocation#19]
Hi,
I am using this in my background service.It is working perfectly fine when we are in app but when app is in background it work for 3-5 times then it start showing same location again and again.
Please help me as early as possible.

**Comment by ocram** [comment]
1. What Android version?
 1. Emulator or real device (which manufacturer)?
 1. What configuration do you use this library with? Can you show how you create and use the instance?
 1. What type of background service? How is it created?
 1. Are you sure the background service is still running after that specified duration?

**Comment by kulwinderSingh30** [comment]
android version 7.0.
model no=redmi note 4.

yes i am sure service running in background because i am getting output in
log.


depedency i am using for simplelocation is v1. 0.1

**Comment by kulwinderSingh30** [comment]
hi,
there is a issue with my phone setting after changing it location start
updating.

**Comment by ocram** [comment]
Thank you!

So has this problem been solved then? If so, could you explain the setting that you needed to change in more detail? That could help others in the future. Thanks!

**Comment by kulwinderSingh30** [comment]
In Redmi note 4 there is a system default app "security" click on that app
then go to battery option. In battery option click on battery saver option
then search for the app created by you click on app then change it to the
no restriction option. After this app will start working.

**Comment by ocram** [comment]
Thanks a lot for sharing that solution!

I knew it must be something like that, which other manufacturers like Huawei have as well, but I didn't know what exactly Xiaomi does.
