### ISSUE TITLE
Location is not giving updated latitude and longitude

### ISSUE THREAD

**Issue by sandeeplondhe** [delight-im/Android-SimpleLocation#21]
When it changes the position it is not updating the latitude and longitude so giving old values instead of giving new latitude and longitude values.

```
        location.setListener(new SimpleLocation.Listener() {

            public void onPositionChanged() {
                // new location data has been received and can be accessed




                    latitude_user = location.getLatitude();
                    longitude_user = location.getLongitude();

}
```

**Comment by ocram** [comment]
1. Can you log something in the `onPositionChanged` callback to see if that method is ever executed at all?
 1. Can you show your call to the `SimpleLocation` constructor?
 1. Did you follow all steps from the README?
