### ISSUE TITLE
calculateDistance not found

### ISSUE THREAD

**Issue by yogeshpaliyal** [delight-im/Android-SimpleLocation#25]
Method Calculate not found.

**Comment by ocram** [comment]
Don’t know how this could happen. If you look into the source code, you see that it’s really there:

 * https://github.com/delight-im/Android-SimpleLocation/blob/adf899da6b9fd55f860979e88e9c247554377683/Source/library/src/main/java/im/delight/android/location/SimpleLocation.java#L584
 * https://github.com/delight-im/Android-SimpleLocation/blob/adf899da6b9fd55f860979e88e9c247554377683/Source/library/src/main/java/im/delight/android/location/SimpleLocation.java#L571

What version did you use in your Gradle dependency for this library?

And what’s the code that you used to call the method? Something like the following?

```java
SimpleLocation.calculateDistance(startLatitude, startLongitude, endLatitude, endLongitude);

// or

SimpleLocation.calculateDistance(startPoint, endPoint);
```
