### ISSUE TITLE
Always updating the last known location rather than the current one.

### ISSUE THREAD

**Issue by Abhinab01** [delight-im/Android-SimpleLocation#3]
Hello mwaclawek,
I am very grateful that you have made this wonderful library available to everyone and it is pretty awesome.

But currently im facing some issues with getting the current location, as the old known location is only getting updated most of the times... And in many devices im only getting (0,0) coordinates...

Is there any way I can correct it and make it update the location to the current one every-time asked for and eliminate the (0,0) coordinate results?...

I really need your help and I shall always be grateful to you for the same... Please help...

**Comment by ocram** [comment]
Thanks for your kind feedback!

What's your code that isn't really working yet? Did you include the call to `beginUpdates()`?

Otherwise, if the default interval between new location updates (10 minutes) does not work for you, you can pass a custom interval (in milliseconds) to the constructor:
https://github.com/delight-im/Android-SimpleLocation/blob/568773416017e7c515f330f5c0f083831b3a2f66/Source/src/im/delight/android/location/SimpleLocation.java#L161

Does that help?

**Comment by Abhinab01** [comment]
Thanks a lot for your kind response... Yes I figured out that I was not
calling beginUpdates(); but like you said, to change the default update
time I need to pass a custom interval (in milliseconds) to the constructor,
but HOW? I'm using your .jar file in my library, How can I edit that?
Please Help... I really need it... :(

Thank You Again... :)

**Comment by ocram** [comment]
Using the JAR is fine, it's possible without changing any library code:

Right now, you're calling the constructor like this:

`location = new SimpleLocation(this);`

You just have to replace that call with the following one:

`location = new SimpleLocation(this, false, false, 5000);`

... to request a new location every 5 seconds. This will drain the battery more than the default interval, of course. You have to try and see what works for you.

If you had the second parameter of the constructor set to `true` like this:

`location = new SimpleLocation(this, true);`

... then keep that parameter as well and just add the two `false` and `5000`.

Please report if that worked :)

**Comment by Abhinab01** [comment]
Thanks a lot.... I'll let you know if it works... :)

**Comment by Abhinab01** [comment]
The edits you suggested, are working like a charm...! But there's a little
problem that my Mobile and some other phones keeps updating the same
location again and again until I restart my phone, but on many other phones
it does updates every 5 seconds as you suggested....

Is there a way I can correct it?

I do call location.beginUpdates(); before I start the rest of the program,
but still I receive the same locations until restarted...

Thank You. :)

**Comment by ocram** [comment]
Thanks, apparently, there's no bug here and everything is working as intended.

If you continue to have problems with some devices that use the same location again and again (what does that mean, exactly?) please check your integration and check if GPS is enabled on the device.

Should you need more help even after debugging your integration, please open a separate issue here. Thank you!

**Comment by Abhinab01** [comment]
Ok I'll check it, Thanks a lot anyways.. :)
