### ISSUE TITLE
precise only upto 3 digits of longitude & lattitude

### ISSUE THREAD

**Issue by SriRamGovardhanam** [delight-im/Android-SimpleLocation#30]
precise only up to 3 digits of longitude & latitude,4th digit is crucial to me ..can u implement this more accurately

**Comment by ocram** [comment]
I don’t think there’s any such limitation here, so there’s nothing to implement more accurately, either.

Can you check your implementation and results again?

The accuracy and precision of the results should only be limited by Java’s `double` data type (which is definitely sufficient) and the accuracy of your device’s location sensors or providers.

**Comment by SriRamGovardhanam** [comment]
No my issue is, it gives different values which differs from 4th decimal(11 meters range) of longitude like "16.3552337,78.55942955499674" , "16.35524006270739,78.5595229" after every time I refresh...I won't care if it starts deflecting from 5th decimal(1.1m not a big deal).

**Comment by ocram** [comment]
First, please make sure you don’t ever call `setBlurRadius` on the `SimpleLocation` instance anywhere in your code.

Apart from that, if the fractional digits change, well, that’s just what the sensor tells us. So what should we do? I don’t think there’s anything that *can be* or *should be* done here. If you can’t handle the raw data from the sensor, just round them as you need them.

**Comment by SriRamGovardhanam** [comment]
can u plz elaborate why setBlurRadius is used for...i really didnt understood what is that actually meant for! 
when I removed and build the project it shows a fixed location coordinates instead of variable location just like for setBlurRadius...and which is better I mean which gives accurate coordinates 
1)without setBlurRadius or
2) with setBlurRadius(1)  (1meter range)

**Comment by ocram** [comment]
Just don’t use it here. It’s meant for making locations less precise for privacy reasons.

Either don’t call it at all or call it with `0` as its argument. That’s what you want here.
