### ISSUE TITLE
GPS UTC time?

### ISSUE THREAD

**Issue by makrolika** [delight-im/Android-SimpleLocation#31]
Hello, is there a UTC time in a GPS signal? Can you extract it for using? I work with lon lat and UTC timestamp.

**Comment by ocram** [comment]
Yes, there are [time signals in GPS](https://en.wikipedia.org/wiki/GPS_signals) that are processed by the receiver, and the information has been added [here](https://github.com/delight-im/Android-SimpleLocation/commit/04d454bf94d2ea3fc9afd3f3c35c9617e15e22fa) and documented [here](https://github.com/delight-im/Android-SimpleLocation/commit/596a1928d9267016abab29f0a6c4e058edd21573).

Please update your dependency for this library to `v1.1.0` and you should be able to call method `getTimestampInMilliseconds` on your instance of class `SimpleLocation`.
