### ISSUE TITLE
Is this library working on background process

### ISSUE THREAD

**Issue by hafiz013** [delight-im/Android-SimpleLocation#34]
Hi there is this library working on background process in order to get latest location in android 6 above.tq

**Comment by ocram** [comment]
I would say this library is neutral when it comes to background process limits.

Whether it works in background processes depends on your app and where you place the calls to this library.

You may be using this library in an `Activity`, `Service`, `IntentService`, `JobService`, `JobIntentService`, etc., and all these contexts have different implications – which you can read about in the Android documentation.
